CC = g++

HEADERS_DIR = headers

CFLAGS = -Wformat=2 -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal \
         -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs \
		 -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions \
		 -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 \
		 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor \
		 -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing \
		 -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

DEBUG = DEBUG
SOURCES_DIR = src
SOURCES = $(wildcard $(SOURCES_DIR)/*.cpp)

BUILD_DIR = build

OBJ_DIR = obj
OBJECTS = $(wildcard $(OBJ_DIR)/*.o)
EXECUTABLE = spu.exe

all: $(SOURCES) $(BUILD_DIR)
	$(CC) $(SOURCES) -o $(BUILD_DIR)/$(EXECUTABLE) -I$(HEADERS_DIR) -D$(DEBUG) $(CFLAGS)

%.o: %.cpp
	$(CC) $(CFLAGS) -I$(HEADERS_DIR) $< -c -o $(OBJ_DIR)/$@

create_build:
	mkdir $(BUILD_DIR)

create_txlib.o:
	$(CC) $(CFLAGS) -I$(HEADERS_DIR) TXLib/TX_Lib.cpp -c -o $(OBJ_DIR)/TX_Lib.o

clean_exe:
	rm $(BUILD_DIR)/*.exe

clean_obj:
	rm $(OBJ_DIR)/*.o

clean:
	rm $(BUILD_DIR)
	rm $(OBJ_DIR)

create_obj:
	$(CC) $(SOURCES) -c -I$(HEADERS_DIR) -D$(DEBUG) $(CFLAGS)
	mv *.o $(OBJ_DIR)

comp_run:
	make create_obj
	make linkage
#.\$(BUILD_DIR)/$(EXECUTABLE)

linkage:
	$(CC) $(OBJECTS) -o $(BUILD_DIR)/$(EXECUTABLE)

create:
	mkdir build
